spring.application.name=qsdta-client
server.port=8090

spring.datasource.url= jdbc:mysql://localhost:3306/qsdta
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update